### PR TITLE
Don't pass parseParam to wrapTracking

### PR DESCRIPTION
**Pull request by benjamn**
The `parseParam` function is just a helper that returns a boolean value, rather than a true parsing function that returns an AST node. When wrapped by `wrapTracking`, which assumes that the result of `parseFunction` is an AST node, `parseParam` becomes unusable in browsers that restrict property accesses on boolean values. For instance, in strict mode in Safari, `true.foo = value` throws "TypeError: Attempted to assign to readonly property."

cc @vjeux @jeffmo

### CODE REVIEW

**Comment by vjeux** [comment]
Cool thanks :)

**Comment by jeffmo** [comment]
I assume you ran npm test right?

**Comment by benjamn** [comment]
@jeffmo yeah, apparently the way to run Esprima tests is to start a server in the root directory of the repo (e.g. with `python -m SimpleHTTPServer`), then load `localhost:8000/test` in the browser. That's what I did, and everything passed.

**Comment by jeffmo** [comment]
You can also just run `npm test` :)

**Comment by benjamn** [comment]
This got merged into upstream esprima#harmony: https://github.com/ariya/esprima/pull/184

**Pull request merged**
