### PR TITLE
Switch from nullable properties to nullable type annotation nodes

### PR DESCRIPTION
**Pull request by gabelevi**
The current way we deal with nullables are by adding `nullable` properties on various nodes. This change switches to wrapping nullable types in a `NullableTypeAnnotation` node. This is a little cleaner since we don't need to add a nullable property on each node. 

The tests were relatively easy to update...just removed all the `nullable: false` and regenerated the three tests that had `nullable: true`

### CODE REVIEW

**Comment by gabelevi** [comment]
Rebased this on top of the new fbtest autogen. Was super easy =D

**Comment by jeffmo** [comment]
Seems legit. The only [weak] feedback I have is that it seems a bit incongruent with how we don't use wrappers for other kinds of annotations (but instead hang these kinds of things as leaf nodes).

**Comment by jeffmo** [comment]
^^ Consider that comment an 'accept' -- such that you can decide to care about it or not and commit (slash "merge") yourself after whatever you decide to do.

(github workflow is weird)

**Comment by gabelevi** [comment]
In general I think wrappers are better, but we use properties instead in order to avoid breaking visitors. Once we get away from the standard AST that people expect, we have more freedom because we're the ones defining the structure of the AST for types and there are no visitors yet to break.

PS I'm not sure if I have the power to merge things myself.

**Pull request merged**
