### PR TITLE
Exclude all tests from npm package.

### PR DESCRIPTION
**Pull request by hughsk**
See: substack/node-browserify#707

This reduces the size of the installed module by ~1.8MB, improving overall install times for dependant modules – made more significant by the fact that there's multiple copies of esprima-fb being installed with larger projects e.g. browserify.

Thanks! :)

### CODE REVIEW

**Comment by jeffmo** [comment]
Nice. Would you mind sending this upstream to https://github.com/ariya/esprima/tree/harmony though? If they're willing to take it there then we can just merge it back downstream here and we'll have less to deal with when tracking upstream in the future

**Comment by aearly** [comment]
This was rejected upstream since they support the --npat option of npm install, which runs the tests.  Also, they support pruning the package through the "files" option of the package json.  This could also help reduce file size -- they only include a handful of the test files.

**Comment by hughsk** [comment]
Oh hey, wasn't aware that `--npat` existed, neat. Sorry I never got round to this! Thanks @aearly for chasing it up. Am I right in thinking that https://github.com/ariya/esprima/commit/ddd4ad9ca63bcff4962c23b54a260f545b84234c just needs to get pulled into fb-esprima in that case?

**Comment by aearly** [comment]
Actually, I misspoke, `npat = true` is a `npm-config (7)` option (it was new to me too).  But you are correct — that one commit is all we need.  It knocks 1 MB off the package size.

**Comment by jeffmo** [comment]
Sorry for the delay in response -- this looks great.
Would you mind signing our CLA here so I can merge this?

code.facebook.com/cla

**Comment by hughsk** [comment]
@jeffmo no problem!

Have signed the CLA – I've also updated the pull request to pull in e069e40621e4e7021ef6d89fc561f1d35566be12 directly :)

**Comment by zpao** [comment]
This actually happened upstream already (https://github.com/ariya/esprima/commit/a93825f66cccb0ebf1ed5b56bc541610a371cbe6) and that made it's way into the harmony branch there and our fb-harmony branch here.

**Pull request closed without merging**
