### PR TITLE
Allow dot (.) in JSXIdentifier to allow for Javascript "namespacing"

### PR DESCRIPTION
**Pull request by jtmalinowski**
This is PR for https://github.com/facebook/react/issues/221, basically we would love to have 

``` javascript
<Namespaced.JSX.Tags /> 
```

We probably need to add tests here, can owner comment on that?

### CODE REVIEW

**Comment by jeffmo** [comment]
We still need to discuss whether we want `.` or `:` (brought this up over on the issue) but either way this should be parsed as a MemberExpression of some kind (or we need a new namespace field on the XJSElement node) in the `<Nspc[.:]Component>` case (rather than an identifier with a dot-operator in it)

**Comment by jeffmo** [comment]
Actually, if we go with `:`, it would be better not to tie things to `MemberExpression` explicitly and let the compiler be responsible for interpreting the meaning of a namespace. That way, the decision of what it means to write `<MyStuff:MyThing />` is left up to the compiler (does it compile to `MyStuff.MyThing`? Or maybe `MyStuff__MyThing`? Or hell maybe even `require("MyStuff/MyThing")` )

Anyway, commenting this here to be sure you're aware that we need to discuss this more before you do anymore work. Let's continue the discussion over in the thread on https://github.com/facebook/react/issues/221

**Comment by jordwalke** [comment]
Good point on that @jeffmo: I think it still holds true even if we decided to go with the `.`.

**Comment by jeffmo** [comment]
Going to close this for now since it sounds like @jakubmal doesn't have time to iterate on it. Thanks for starting the discussion around this, though!

**Pull request closed without merging**
