### PR TITLE
Use sensible whitespace in fbtest generator.

### PR DESCRIPTION
**Pull request by zpao**
- Removes trailing whitespace
- Adds newline at end of file.

This makes it so editors that modify whitespace on save will leave the
file in the correct state.

Because https://github.com/facebook/esprima/pull/85#discussion-diff-23480413. cc @spicyj

### CODE REVIEW

**Comment by sophiebits** [comment]
lgtm

**Comment by zpao** [comment]
Lint is failing with node 0.11.15 but not node 0.11.14. It's not our code but jslint code failing to run, which is weird and actually looks like it might be a bug in jslint... Lint is passing in other node environments. We should maybe let 0.11.x fail.

**Comment by jeffmo** [comment]
Can you try rolling back the jslint dep version and see if you can find a version that doesn't fail for now?

**Comment by zpao** [comment]
I don't think so but I didn't try too hard. The version of jslint is from 2013. Updating actually results in the lint code running but then it fails for linting reasons.

**Comment by jeffmo** [comment]
Oh I didn't read your previous comment correctly -- it's the node version that's failing, not the jslint version.

In that case, can you just take 0.11 out of the travis config file? 0.11 is unstable anyway...

**Comment by zpao** [comment]
:thumbsup: Actually, it might be even better to bring in upstream again since they just fixed this (stopped using jslint entirely)

**Comment by zpao** [comment]
Rebased and all passing.

**Pull request merged**
