### PR TITLE
Fix duplicate property error for property name literals in class definitions

### PR DESCRIPTION
**Pull request by fkling**
Duplicate method definition detection doesn't treat string and number literal property names correctly. The following code raises a "Illegal duplicate property in class definition" error: 

```
class A { 42() {} "foo"() {} }
```

This happens because we used `key.name` to get the "name" of the property name, but `.name` only exists for IdentifierName, not for StringLiteral or NumericLiteral.

This changes the code to use either `.name` or `.value` depending on the type of property name.

It also fixes another problem: `class A { foo() {} "foo"() {}}` should have thrown a duplicate property error, but it didn't.

### CODE REVIEW

**Comment by RReverser** [comment]
This should be rather PR to esprima#harmony as it's not JSX-specific issue and would be better to fix this on top level.

Also, regarding `class A { foo() {} "foo"() {}}` - AFAIR, computed properties are excluded from duplicate check by spec. Even if they're regular string literals inside; yes, I know it's embarrassing.

**Comment by RReverser** [comment]
Even better - duplicate check should be eliminated now. Proofs:
1. [Rev26 ES6 spec draft](http://esdiscuss.org/topic/new-rev26-es6-draft-now-available): `Eliminated duplicate property name restrictions on object literals and class definitions`
2. [esdiscuss thread](http://esdiscuss.org/topic/duplicate-property-names-was-re-new)

**Comment by fkling** [comment]
> Even better - duplicate check should be eliminated now. 

That's actually I concern I had but forgot to mention it. I couldn't find anything in the spec that describes this behavior, except for `constructor`. I got [confused by](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-in-the-6th-edition)

> Early error relating to duplicate property names in Object Initializers have been eliminated in Edition 6.

which doesn't mention classes. However, I didn't realize that this section just seems to mention differences between ES6 and ES5, not earlier versions of ES6.

> Also, regarding class A { foo() {} "foo"() {}} - AFAIR, computed properties are excluded from duplicate check by spec.

`"foo"() {}` is not a computed property here. It's a [_LiteralPropertyName_](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-object-initializer). Doesn't matter now anyways :) 

If someone else hasn't done it already, I will remove the duplicate property check.

**Comment by RReverser** [comment]
> "foo"() {} is not a computed property here. It's a LiteralPropertyName. Doesn't matter now anyways :) 

Yeah, sorry. Just mean that they both appeared under the same elimination :)

**Comment by RReverser** [comment]
> If someone else hasn't done it already, I will remove the duplicate property check.

Please submit it as issue to `ariya/esprima` (if it doesn't have one yet) and send PR to it so we could all get same updated version from mainstream.

**Comment by fkling** [comment]
Will do! Thanks for pointing me in the right direction!

**Comment by fkling** [comment]
FWIW: https://github.com/ariya/esprima/pull/286

**Pull request closed without merging**
