### PR TITLE
Parse object type indexer properties

### PR DESCRIPTION
**Pull request by gabelevi**
This is a syntax for declaring the types of keys and values when you index into unknown properties on objects and interfaces. 

```
var string_to_int_map: { [index: string]: number } = {};
```

[This syntax comes from typescript](http://www.typescriptlang.org/Handbook#interfaces-array-types)

### CODE REVIEW

**Comment by jeffmo** [comment]
Code-wise, this looks good. I'm pretty unsatisfied that it looks like you can specify the type of an object key as anything other than `string` though (there's no such option in JS)

**Comment by RReverser** [comment]
> I'm pretty unsatisfied that it looks like you can specify the type of an object key as anything other than string though (there's no such option in JS)

It can be `number` for indexing. Or, with proper transpiler, could even convert anything else to ES6 `Map`.

**Comment by jeffmo** [comment]
@RReverser: Key's can't be `number` in real life -- object keys are always coerced to a string before they're stored in JS.

A couple examples:

``` js
typeof Object.keys(['a'])[0]; // 'string'

for (var key in {42: 'hai'}) {
  typeof key; // string
}
```

**Comment by RReverser** [comment]
@jeffmo I'm definitely aware of that :)

**Comment by RReverser** [comment]
@jeffmo Strictly speaking, engines actually use real numbers under the hood for any array-like objects where you put `{0:'a', 1:'b'}`. But that doesn't matter.

What does is that for those array-like objects (`Array`, `Uint8Array`, `jQuery(...)`, etc.) having ability to set strict index type to `number` is often useful.

**Pull request merged**
