### PR TITLE
Support future regular expression flags

### PR DESCRIPTION
**Pull request by mathiasbynens**
This makes Esprima not throw on regular expression literals that use the new `u` and `y` flags in ES6.

This allows [regexpu](https://github.com/mathiasbynens/regexpu) to work.

### CODE REVIEW

**Comment by RReverser** [comment]
Shouldn't this be submitted to esprima#harmony so it could be merged here later together with other commits?

**Comment by mathiasbynens** [comment]
It should go into both `esprima#master` and `esprima#harmony` IMHO, because this is not limited to ES6/Harmony. It’s about every new regex flag that will ever be added to the language. Also note that `/y` has been around in SpiderMonkey for a long time as a proprietary extension – it would be nice if Esprima could parse it.

**Comment by mathiasbynens** [comment]
Sorry, I thought this was the upstream Esprima tracker.

@RReverser The upstream PR for the master branch is https://github.com/ariya/esprima/pull/264, but since it’s bigger in scope it will probably take a while until it’s finalized and merged. **Update:** This is now merged.

**Comment by mathiasbynens** [comment]
Upstream patch for the harmony branch: https://github.com/ariya/esprima/pull/288/files

**Comment by mathiasbynens** [comment]
This is now merged in the upstream harmony branch: https://github.com/ariya/esprima/commit/e6e83f07968e386c33cf291f05fff001ac9029ef

Should I close this PR?

**Comment by RReverser** [comment]
@mathiasbynens It will be definitely pulled in on next upstream merge, but I think you can ping someone (@zpao? @jeffmo?) if that's critical for you to get this in soon.

**Comment by mathiasbynens** [comment]
Closing this issue as merging with upstream now has the same result. @jeffmo @zpao I’d appreciate it if you could do this one of these days, if you get a chance, and then release a new version of esprima-fb.

**Comment by jeffmo** [comment]
@mathiasbynens : 7001.0001.000 just published which includes your upstream patch:

https://github.com/facebook/esprima/commit/1f5a0a0d68844923570c1d71660b152090a51c04

**Comment by mathiasbynens** [comment]
@jeffmo Thanks! :+1:

**Pull request closed without merging**
