### PR TITLE
fix loc.end for JSXEmptyExpression

### PR DESCRIPTION
**Pull request by jenseng**
ensure that it correctly handles line terminators, whether part of the
empty expression, or block comment inside it.

this is particularly important for recast or other tools that care about
comments inside jsx expressions. recast in particular will error out if
there is a loc mismatch between the comment and its corresponding node.
see https://github.com/benjamn/recast/issues/175 for more context.

the AST for the newly added tests differs only in its JSXEmptyExpression
loc.end data when run against the old code:

```
1058c1058
<                             end: { line: 1, column: 6 }

---
>                             end: { line: 2, column: 1 }
1194c1194
<                             end: { line: 1, column: 38 }

---
>                             end: { line: 5, column: 11 }
```

### CODE REVIEW

**Comment by jenseng** [comment]
fwiw node 0.11 and 0.10 builds both passed, and i'm pretty sure this commit isn't the reason why the 0.8.0 build failed :wink:

that said, i'm definitely open to suggestions if there's a better way to fix this :thumbsup:

**Comment by zpao** [comment]
Yea, the node v0.8 problem definitely isn't your fault, that's an npm issue :)

This seems totally reasonable to me. @jeffmo - any comments before I take it?

**Comment by jeffmo** [comment]
If allthetests pass (internally and externally), lgtm

**Comment by jenseng** [comment]
woot thx :+1:

**Pull request merged**
