### PR TITLE
XJSNamespacedName to replace namespace in XJSIdentifier token

### PR DESCRIPTION
**Pull request by syranide**
Follow-up to https://github.com/facebook/esprima/pull/7

As usual, just shout if there's anything you disagree with or want done differently.

I'm kind of inclined to change `XJSIdentifier.name` to `XJSIdentifier.value` to signify that it's actually a value now, `name` kind of suggests that it is an object. Also, using `XJSIdentifier.value` would make it distinct from `XJSNamespacedName.name`. But it's a rather disruptive change.

PS. http://stackoverflow.com/questions/5308816/how-to-use-git-merge-squash, although I think it will squash the commit messages too, which is not desirable.

### CODE REVIEW

**Comment by syranide** [comment]
cc @jeffmo

**Comment by jeffmo** [comment]
I think we need a corresponding update to the react transforms that goes with this right? It'd be good to have that ready to go + testable next to this one so they can vet each other

**Comment by syranide** [comment]
Hmm, yeah I wonder what I had in mind here.

I'm not sure if anything _actually_ needs to be done in the React transforms, but I think I simply held off to see if you agreed with the overall "design" first. I'll look into it a little later.

**Comment by syranide** [comment]
Tested it with no issues, looked through the transform code and couldn't find anything that should be updated. So unless you have any input, this PR is all that is needed.

PS. Do we have any test(file)s for JSX right now in React? I should add member expressions then.

**Pull request merged**
