### PR TITLE
Merge jquery/harmony

### PR DESCRIPTION
**Pull request by zpao**
I'm doing this merge after weeks instead of months because the pain is too real. There were only a couple commits but they should fix my issue with using eslint (thanks @mikesherov!) and the other is @jeffmo.

### CODE REVIEW

**Comment by mikesherov** [comment]
:+1:

**Comment by mikesherov** [comment]
There's going to be another set of patches for template literals soon. Will keep you in the loop

**Comment by zpao** [comment]
Cool, I'm actually hold off on merging. Issue incoming that's going to prevent us from bringing this in right now.

**Comment by zpao** [comment]
Temporarily merged in #107 and #108 to test the mergability and run tests.

**Comment by zpao** [comment]
ugghhh, I forgot to strip those "temporary" merges so now the history here is super gross. Oh well.
screen shot 2015-04-02 at 2 35 14 pm

**Pull request merged**
